[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.dependencies]
criterion = "0.8"
insta = { version = "1.46", features = ["glob", "json"] }
line-index = "0.1"
lspt = "0.3"
rustc-hash = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
similar-asserts = "1.7"
